### ISSUE TITLE
...ipsectunnel.a(_go_.o): error reading unexpected EOF

### ISSUE THREAD

**Issue by scottdware** [PaloAltoNetworks/pango#11]
I'm running a simple script on Go 1.12.4, and receiving the following error when issuing "go run palo.go"

`2019/05/10 18:19:33 C:\Users\XXX\Documents\Go\pkg\windows_amd64\github.com\PaloAltoNetworks\pango\netw\ipsectunnel.a(_go_.o): error reading unexpected EOF`

The script I'm trying to run is as follows:

```Go
package main

import (
	"log"

	"github.com/PaloAltoNetworks/pango"
)

func main() {
	var err error

	c := &pango.Firewall{Client: pango.Client{
		Hostname: "192.168.120.128",
		Username: "admin",
		Password: "admin",
		Logging:  pango.LogAction | pango.LogOp,
	}}

	if err = c.Initialize(); err != nil {
		log.Printf("Failed to initialize client: %s", err)
		return
	}

	log.Printf("Initialize ok")
}
```

**Comment by shinmog** [comment]
Can you `go test ./...` the `pango` library?

**Comment by scottdware** [comment]
I ran that, and got the following output:

```
PS C:\Users\XXX\Documents\Go\src\github.com\PaloAltoNetworks\pango> go test
# github.com/PaloAltoNetworks/pango.test
2019/05/11 13:18:01 C:\Users\XXX\Documents\Go\pkg\windows_amd64\github.com\PaloAltoNetworks\pango\netw\ipsectunnel.a(_go_.o): error reading unexpected EOF
FAIL    github.com/PaloAltoNetworks/pango [build failed]
PS C:\Users\XXX\Documents\Go\src\github.com\PaloAltoNetworks\pango>
```

**Comment by shinmog** [comment]
Ok, so you're still getting errors with ".o" (compiled) files.

I'd like to try and determine if your error is with the source code that produced the compiled libs or if it's the compiled libs themselves.

I haven't done much with golang on Windows, but since it's a compiled file that's giving you errors, maybe delete them (or if you want to be conservative, move them out of the way temporarily) and try to do `go test ./...` again?  The repo is currently at pango v0.1.1, so depending on when you cloned the repo, you could also try updating the code.

**Comment by scottdware** [comment]
Ok, I'll give that a shot! I just cloned (`go get github.com/PaloAltoNetworks/pango`) the repo right before I started this.

**Comment by scottdware** [comment]
Ok, so I think I see the problem. I'm trying to run this on my work laptop, and I think there are some things with the build (Symantec) that are causing this. Each time I run the `go test` or even try running the script above, I have gotten a weird exit status, and soon after, get a message from Symantec Endpoint Protection.

If I run this on my Linux VM I have in the "cloud" - everything works just fine. I'm going to close this and investigate more on my own. Thanks for the quick response and help!
