### ISSUE TITLE
security policies not getting created

### ISSUE THREAD

**Issue by reneherrero** [PaloAltoNetworks/pango#37]
When creating objects and security policies via Panorama, objects get created but the security policies don't.

I tried copying an existing policy to make sure I wasn't just making a mistake in a field, same thing. Here's a stripped piece of code for readability:
```
	pan := &pango.Panorama{Client: pango.Client{
		Hostname: "w.x.y.z",
		Username: "admin",
		Password: "admin",
		Logging:  pango.LogAction | pango.LogOp,
	}}
	if err = pan.Initialize(); err != nil {
		log.Printf("Failed to initialize client: %s", err)
		return
	}
	existingPolicy, err := pan.Policies.Security.Get("MyDeviceGroup", util.PreRulebase, "ExistingPolicy")
	if err != nil {
		log.Panic(err)
	}
	copiedPolicy := security.Entry{}
	copiedPolicy.Copy(existingPolicy)
	copiedPolicy.Name = "CopiedPolicy"
	pan.Policies.Security.Set("MyDeviceGroup", util.PreRulebase, copiedPolicy)
        resp, err := pan.Commit("Added test policy", nil, true, true, false, true)
```

Any tips?  Thanks,

**Comment by shinmog** [comment]
Ok, there are a few things going on here, but one of the issues is that the rule type and description fields are optional in the XML schema, so I've fixed this in the code now.

There is another element at play here, however; a quirk of how the GUI creates security rules.  It looks like if you use the GUI to create a security rule and you leave the type as `universal` then when the GUI creates the rule, the XML it sends actually doesn't contain the rule type in the XML sent.  This means that when you retrieve the security rule's spec using `Get()`, the `Type` param is an empty string, because the XML that created the rule didn't specify this value, so the returned XML is also empty.

There is one more additional quirk specifically with security rule creation:  I would highly recommend using either [VerifiableSet()](https://godoc.org/github.com/PaloAltoNetworks/pango/poli/security#Panorama.VerifiableSet) or [VerifiableEdit()](https://godoc.org/github.com/PaloAltoNetworks/pango/poli/security#Panorama.VerifiableEdit), and the reasoning is contained in the docstrings for these functions.

Finally, the new [commit normalizations](https://godoc.org/github.com/PaloAltoNetworks/pango/commit) have changed how commits are performed in pango.  Based on the function signature I see in your code, you're using an older version of pango, so when you upgrade you'll need to change your commits to this new style.

**Comment by reneherrero** [comment]
Appreciate the prompt turnaround.

I don't need the copy, I just tried that to rule out the fact that I was maybe not setting all the fields correctly

I'm using go mod, it automatically pulled `v0.4.0`.  Updated the `go.mod` file to `master` and it automatically changed it to `v0.4.1-0.20201208215211-148242720294`

Updated to VerifiableSet but struggling with the commit now.  Getting a `invalid client cli` error.  Stepping through your code...

**Comment by reneherrero** [comment]
Very appreciative of the lightning fast turnaround so please don't take this the wrong way: a few examples would be very helpful

**Comment by reneherrero** [comment]
Ok, now I see what's up.  It looks like `false error` for lack of a better name, it's actually creating the policy.

Here's what I think the version numbers are:
Software Version | 8.1.16
Application Version | 769-4439

**Comment by shinmog** [comment]
Example of using the new commit normalization..?  There's an example that is compiled as part of the tests to make sure I didn't break anything:

https://github.com/PaloAltoNetworks/pango/blob/master/example_firewall_commit_test.go

**Comment by reneherrero** [comment]
Thanks for that.  Like I said, it is working now, just returning an error despite having the correct result.

Any chance we can hookup offline?  I'm reluctant to put my code here for obvious reasons. Zack from your team is here with me...

Remove spaces and replace the at: rene _ herrero at dell . com
